---
abstract: 'add code smell to your Moose attributes'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Fatal: 0
  Test::More: 0.61
  thanks: 0.001
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: MooseX::FunkyAttributes
name: MooseX-FunkyAttributes
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Exporter::Everything: 0.001
  Hash::FieldHash: 0
  Moose: 2.00
  aliased: 0
  namespace::autoclean: 0
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=MooseX-FunkyAttributes
  homepage: https://metacpan.org/release/MooseX-FunkyAttributes
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-moosex-funkyattributes
version: 0.002
